import type { Material } from './types'

export const referenceMaterials: Material[] = [
  {
    id: 'env-concrete',
    name: '普通混凝土',
    kind: 'structure',
    density: 2400,
    conductivity: 1.74,
    factor: 0.13,
    lifespan: 60,
    source: '教学示例参数 · 混凝土',
    description: '用于演示质量法计算；工程中应按实际强度等级校核。',
    custom: false,
  },
  {
    id: 'env-aerated',
    name: '蒸压加气混凝土',
    kind: 'structure',
    density: 600,
    conductivity: 0.18,
    factor: 0.32,
    lifespan: 60,
    source: '教学示例参数 · 轻质砌体',
    description: '简化干态导热系数，不含灰缝影响。',
    custom: false,
  },
  {
    id: 'env-brick',
    name: '烧结多孔砖',
    kind: 'structure',
    density: 1400,
    conductivity: 0.58,
    factor: 0.24,
    lifespan: 60,
    source: '教学示例参数 · 多孔砖',
    description: '密度为构造等效密度，需与实际孔洞率一致。',
    custom: false,
  },
  {
    id: 'env-mineral',
    name: '岩棉板',
    kind: 'insulation',
    density: 120,
    conductivity: 0.04,
    factor: 1.2,
    lifespan: 30,
    source: '教学示例参数 · 岩棉',
    description: '仅计材料层，未包含锚固件与粘结层。',
    custom: false,
  },
  {
    id: 'env-woodfiber',
    name: '木纤维保温板',
    kind: 'insulation',
    density: 160,
    conductivity: 0.046,
    factor: 0.55,
    lifespan: 30,
    source: '教学示例参数 · 木纤维',
    description: '本模型不抵扣生物源碳储存。',
    custom: false,
  },
  {
    id: 'env-foamglass',
    name: '泡沫玻璃板',
    kind: 'insulation',
    density: 150,
    conductivity: 0.058,
    factor: 1.05,
    lifespan: 50,
    source: '教学示例参数 · 泡沫玻璃',
    description: '闭孔材料演示参数，实际数值依制造方法而变。',
    custom: false,
  },
  {
    id: 'env-lime',
    name: '石灰砂浆',
    kind: 'finish',
    density: 1700,
    conductivity: 0.81,
    factor: 0.12,
    lifespan: 20,
    source: '教学示例参数 · 砂浆',
    description: '按每次整体替换计算，不含后期碳化修正。',
    custom: false,
  },
  {
    id: 'env-gypsum',
    name: '石膏板',
    kind: 'finish',
    density: 800,
    conductivity: 0.22,
    factor: 0.26,
    lifespan: 25,
    source: '教学示例参数 · 石膏',
    description: '不计龙骨及接缝材料，需另建构造层。',
    custom: false,
  },
]
